Propeller-GCC Libraries: I2C_OPS Struct Reference
I2C_OPS Struct Reference
#include <i2c.h>
Public Attributes
int(* close)(I2C *dev)
int(* read)(I2C *dev, int address, uint8_t *buffer, int count, int stop)
int(* readMore)(I2C *dev, uint8_t *buffer, int count, int stop)
int(* write)(I2C *dev, int address, uint8_t *buffer, int count, int stop)
int(* writeMore)(I2C *dev, uint8_t *buffer, int count, int stop)
Detailed Description
Definition at line 41 of file i2c.h.
Member Data Documentation
close
int(* I2C_OPS::close) (I2C *dev)
Definition at line 42 of file i2c.h.
Referenced by i2cClose().
read
int(* I2C_OPS::read) (I2C *dev, int address, uint8_t *buffer, int count, int stop)
Definition at line 43 of file i2c.h.
Referenced by i2cRead().
readMore
int(* I2C_OPS::readMore) (I2C *dev, uint8_t *buffer, int count, int stop)
Definition at line 44 of file i2c.h.
Referenced by i2cReadMore().
write
int(* I2C_OPS::write) (I2C *dev, int address, uint8_t *buffer, int count, int stop)
Definition at line 45 of file i2c.h.
Referenced by i2cWrite().
writeMore
int(* I2C_OPS::writeMore) (I2C *dev, uint8_t *buffer, int count, int stop)
Definition at line 46 of file i2c.h.
Referenced by i2cWriteMore().
The documentation for this struct was generated from the following file:
include/i2c.h